BookStore.WebUI/Controllers/SubscriberController.cs
using BookStore.WebUI.Dtos.ProductDtos;
using BookStore.WebUI.Dtos.QuoteDtos;
using BookStore.WebUI.Dtos.SubscriberDtos;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;

namespace BookStore.WebUI.Controllers
{
    public class SubscriberController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;

        public SubscriberController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        public async Task<IActionResult> SubscriberList()
        {
            var client = _httpClientFactory.CreateClient();
            var responseMessage = await client.GetAsync("https://localhost:7293/api/Subscribers");
            if (responseMessage.IsSuccessStatusCode)
            {
                var jsonData = await responseMessage.Content.ReadAsStringAsync();
                var values = JsonConvert.DeserializeObject<List<ResultSubscriberDto>>(jsonData);
                return View(values);
            }

            return View();

        }

        [HttpGet]
        public IActionResult CreateSubscriber()
        {
            return View();
        }

        [HttpPost]

        public async Task<IActionResult> CreateSubscriber(CreateSubscriberDto createSusbcriberDto)
        {
            var client = _httpClientFactory.CreateClient();
            var jsonData = JsonConvert.SerializeObject(createSusbcriberDto);
            StringContent content = new StringContent(jsonData, Encoding.UTF8, "application/json");
            var responseMessage = await client.PostAsync("https://localhost:7293/api/Subscribers", content);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("SubscriberList");
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> UpdateSubscriber(int id)
        {
            var client = _httpClientFactory.CreateClient();
            var responseMessage = await client.GetAsync("https://localhost:7293/api/Subscribers/GetSubscriber?id=" + id);
            if (responseMessage.IsSuccessStatusCode)
            {
                var jsonData = await responseMessage.Content.ReadAsStringAsync();
                var values = JsonConvert.DeserializeObject<GetByIdSubscriberDto>(jsonData);
                return View(values);
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> UpdateSubscriber(UpdateSubscriberDto updateSubscriberDto)
        {
            var client = _httpClientFactory.CreateClient();
            var jsonData = JsonConvert.SerializeObject(updateSubscriberDto);
            StringContent content = new StringContent(jsonData, Encoding.UTF8, "application/json");
            var responseMessage = await client.PutAsync("https://localhost:7293/api/Subscribers", content);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("SubscriberList");
            }

            return View();
        }

        public async Task<IActionResult> DeleteSubscriber(int id)
        {

            var client = _httpClientFactory.CreateClient();
            await client.DeleteAsync("https://localhost:7293/api/Subscribers?id=" + id);
            return RedirectToAction("SubscriberList");
        }

        [HttpPost]
        public async Task<IActionResult> SendMailToAll()
        {
            var client = _httpClientFactory.CreateClient();
            var content = new StringContent("{}", Encoding.UTF8, "application/json");

            var response = await client.PostAsync("https://localhost:7293/api/Subscribers/SendMailToAll", content);

            if (response.IsSuccessStatusCode)
                TempData["result"] = "The email was successfully sent to all subscribers.";
            else
                TempData["result"] = "Something went wrong while sending emails.";

            return RedirectToAction("SubscriberList");
        }



    }


}

BookStore.WebUI/Views/Subscriber/CreateSubscriber.cshtml
@model BookStore.WebUI.Dtos.SubscriberDtos.CreateSubscriberDto
@{
    ViewData["Title"] = "Create Subscriber";
    Layout = "~/Views/AdminLayout/Layout.cshtml";
}


<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-8">

            <div class="card shadow-lg">
                <div class="card-header text-bg-light text-white text-center">
                    <h4><i class="fas fa-plus-circle"></i> Create New Subscriber</h4>
                </div>
                <div class="card-body">
                    <form method="post">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="mb-3">
                                    <label class="form-label"><i class="fas fa-tag"></i> Subscriber Email</label>
                                    <input type="text" asp-for="Email" class="form-control" placeholder="Enter email" required />

                                    <br />
                                    <button type="submit" class="btn btn-dark"><i class="fas fa-save"></i> Save</button>
                                </div>
                            </div>

                        </div>


                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

BookStore.WebUI/Views/Subscriber/SubscriberList.cshtml
@model List<BookStore.WebUI.Dtos.SubscriberDtos.ResultSubscriberDto>
@{
    ViewData["Title"] = "Subscriber List";
    Layout = "~/Views/AdminLayout/Layout.cshtml";
    int count = 0;
}


<div class="container">
    <table class="table table-styling">

        <tr>
            <th>#</th>
            <th>Subscriber Email</th>
            <th>Delete</th>
            <th>Update</th>
        </tr>
        @foreach (var item in Model)
        {
            count++;
            <tr>
                <td>@count</td>
                <td>@item.Email</td>
                <td><a href="/Subscriber/DeleteSubscriber/@item.SubscriberId" class="btn btn-danger"><i class="fa fa-trash"></i></a></td>
                <td><a href="/Subscriber/UpdateSubscriber/@item.SubscriberId" class="btn btn-info"><i class="fa fa-pen"></i></a></td>
            </tr>
        }

    </table>

    <div class="d-flex gap-2">
        <a href="/Subscriber/CreateSubscriber" class="btn btn-primary">
            <i class="fa fa-plus"></i> Add New Subscriber
        </a>

        <form asp-action="SendMailToAll" asp-controller="Subscriber" method="post">
            <button type="submit" class="btn btn-outline-info">
                <i class="fa fa-envelope"></i> Send Mail to All
            </button>
        </form>
    </div>

</div>

@section Scripts {
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    @if (TempData["result"] != null)
    {
        <script>
            Swal.fire({
                icon: 'success',
                title: 'Done!',
                text: '@TempData["result"]',
                confirmButtonColor: '#3085d6'
            });
        </script>
    }
}

BookStore.WebUI/Views/Subscriber/UpdateSubscriber.cshtml
@model BookStore.WebUI.Dtos.SubscriberDtos.GetByIdSubscriberDto
@{
    ViewData["Title"] = "Update Subscriber";
    Layout = "~/Views/AdminLayout/Layout.cshtml";
}


<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-8">

            <div class="card shadow-lg">
                <div class="card-header text-bg-light text-white text-center">
                    <h4><i class="fas fa-plus-circle"></i> Update Subscriber</h4>
                </div>
                <div class="card-body">
                    <form asp-action="UpdateSubscriber" asp-controller="Subscriber" method="post">
                        <input type="hidden" asp-for="SubscriberId" />
                        <div class="row">
                            <div class="col-md-12">
                                <div class="mb-3">
                                    <label class="form-label"><i class="fas fa-tag"></i> Subscriber Email</label>
                                    <input type="text" asp-for="Email" class="form-control" placeholder="Enter email" required />

                                    <br />
                                    <button type="submit" class="btn btn-dark"><i class="fas fa-sync"></i>Update</button>
                                </div>
                            </div>

                        </div>


                    </form>
                </div>
            </div>
        </div>
    </div>
</div>